# Generated by Django 4.1.2 on 2022-10-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='add_to_saved',
        ),
    ]
