# Generated by Django 4.1.2 on 2022-10-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0003_order_product_order_status_orderproduct_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
