# Generated by Django 4.1.2 on 2022-10-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0004_remove_orderproduct_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like',
        ),
    ]
