# Generated by Django 4.1.2 on 2022-10-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0006_alter_orderproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='modelname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
