# Generated by Django 4.1.2 on 2022-10-17 19:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0009_rename_user_orderproduct_author_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('product', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productquantity',
            field=models.PositiveIntegerField(default=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=13),
            preserve_default=False,
        ),
    ]
