# Generated by Django 4.1.2 on 2022-10-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0010_alter_product_managers_product_productquantity_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
