# Generated by Django 4.1.2 on 2022-10-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0014_orderproduct_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='total',
        ),
    ]
