# Generated by Django 4.1.2 on 2022-10-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0015_remove_orderproduct_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
