# Generated by Django 4.1.2 on 2022-10-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0017_alter_orderproduct_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='total',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
