# Generated by Django 4.1.2 on 2022-10-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0018_alter_orderproduct_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='total',
        ),
    ]
