# Generated by Django 4.1.2 on 2022-10-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0020_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=30),
        ),
    ]
