# Generated by Django 4.1.2 on 2022-10-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0024_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productquantity',
            field=models.IntegerField(),
        ),
    ]
