# Generated by Django 4.1.2 on 2022-11-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0025_alter_product_productquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
