# Generated by Django 4.1.2 on 2022-11-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasine', '0026_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
